[package]
name = "robot"
version = "0.1.0"
edition = "2024"

[dependencies]
raven = { path = "../raven" }
bno08x = { path = "../bno08x" }
rppal = "0.22.1"

[[bin]]
name = "robot"
path = "src/main.rs"
